import type { QuizQuestion } from '@/lib/chat/types';

export const QUIZZES: QuizQuestion[] = [
  {
    id: 'js-nan',
    topic: 'JavaScript',
    prompt: 'What does `typeof NaN` evaluate to in JavaScript?',
    options: ['"undefined"', '"number"', '"NaN"', '"object"'],
    correctIndex: 1,
    explanation: 'Per the IEEE 754 floating-point specification, NaN is categorized as a numerical value representing an unrepresentable math result. To test for NaN, use `Number.isNaN(val)`.',
    hint: 'Think about the IEEE 754 floating-point standard used by JS numbers.',
    difficulty: 'beginner',
  },
  {
    id: 'react-keys',
    topic: 'React',
    prompt: 'Why does React require a unique `key` prop on elements rendered in a list?',
    options: [
      'To assign unique CSS classes for styling',
      'To identify item identity across renders during Reconciliation',
      'To automatically sort the array alphabetically',
      'To prevent JavaScript memory leaks',
    ],
    correctIndex: 1,
    explanation: 'React uses the `key` prop to match virtual DOM nodes between renders. Stable keys allow React to reorder or preserve stateful components rather than unmounting and recreating them.',
    hint: 'It relates to the Diffing algorithm and component state preservation.',
    difficulty: 'intermediate',
  },
  {
    id: 'nextjs-rsc',
    topic: 'Next.js',
    prompt: 'What is the primary architectural benefit of React Server Components (RSC) in Next.js App Router?',
    options: [
      'Enables 120 FPS client animations',
      'Zero client bundle size contribution for server-only dependencies',
      'Automatically generates unit test suites',
      'Replaces all CSS with inline styles',
    ],
    correctIndex: 1,
    explanation: 'RSC execute only on the server and stream a serialized UI format. Heavy dependencies used on the server (like markdown parsers or DB drivers) never get sent to the client browser.',
    hint: 'Think about JavaScript bundle size shipped over the network.',
    difficulty: 'intermediate',
  },
  {
    id: 'js-float',
    topic: 'JavaScript',
    prompt: 'What does the expression `0.1 + 0.2 === 0.3` evaluate to in JavaScript?',
    options: ['true', 'false', 'undefined', 'TypeError'],
    correctIndex: 1,
    explanation: 'Because JavaScript uses IEEE 754 binary floating-point numbers, 0.1 and 0.2 cannot be represented with exact precision in binary (yielding ~0.30000000000000004). Use `Math.abs((0.1 + 0.2) - 0.3) < Number.EPSILON`.',
    hint: 'Computers calculate numbers in base 2 (binary), not base 10.',
    difficulty: 'beginner',
  },
  {
    id: 'css-axis',
    topic: 'CSS',
    prompt: 'In a Flex container with `flex-direction: row`, which property aligns child items along the vertical axis?',
    options: ['justify-content', 'align-items', 'align-content', 'place-self'],
    correctIndex: 1,
    explanation: 'In `row` direction, the Main Axis is horizontal (governed by `justify-content`), while the Cross Axis is vertical (governed by `align-items`).',
    hint: 'Main axis is horizontal; cross axis is vertical.',
    difficulty: 'beginner',
  },
  {
    id: 'interstellar-time',
    topic: 'Interstellar',
    prompt: 'On Miller’s ocean planet in Christopher Nolan’s *Interstellar*, how much Earth time passes for every 1 hour spent on the surface?',
    options: ['1 month', '1 year', '7 years', '25 years'],
    correctIndex: 2,
    explanation: 'The extreme gravitational field of the supermassive black hole Gargantua creates massive gravitational time dilation: 1 hour on Miller’s planet corresponds to approximately 7 Earth years.',
    hint: 'Gargantua’s gravity slows down time dramatically — think in years, not months.',
    difficulty: 'intermediate',
  },
  {
    id: 'ts-satisfies',
    topic: 'TypeScript',
    prompt: 'What is the key advantage of TypeScript’s `satisfies` operator over type annotations (`: Type`)?',
    options: [
      'It disables type checking entirely',
      'It validates that a value conforms to a type without widening its specific literal type',
      'It automatically compiles TypeScript to WebAssembly',
      'It replaces runtime unit tests',
    ],
    correctIndex: 1,
    explanation: '`satisfies` asserts compatibility with an interface or type contract while preserving the most specific literal types and autocomplete inferences of the original expression.',
    hint: 'Preserves literal types rather than widening them.',
    difficulty: 'expert',
  },
  {
    id: 'js-event-loop',
    topic: 'JavaScript',
    prompt: 'When the call stack is busy, where do resolved Promise callbacks (`.then` handlers) wait?',
    options: [
      'On the call stack itself',
      'In the microtask queue',
      'In the Web API registry',
      'In the event loop backlog',
    ],
    correctIndex: 1,
    explanation: 'Resolved promises enqueue microtasks. The event loop drains the microtask queue whenever the call stack empties, before moving on to macrotasks or rendering.',
    hint: 'Microtasks run before the next macrotask or render.',
    difficulty: 'intermediate',
  },
  {
    id: 'js-closure-loop',
    topic: 'JavaScript',
    prompt: 'What does this log? `for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 0); }`',
    options: ['0 1 2', '3 3 3', 'undefined undefined undefined', 'A TypeError'],
    correctIndex: 1,
    explanation: '`var` creates one shared binding across loop iterations, and the callbacks run after the loop finishes (when `i` is already 3). Declaring with `let` gives each iteration its own binding.',
    hint: '`var` has one shared binding across loop iterations.',
    difficulty: 'intermediate',
  },
  {
    id: 'react-useeffect-cleanup',
    topic: 'React',
    prompt: 'When does the cleanup function returned from `useEffect` run?',
    options: [
      'Only when the component unmounts',
      'Before the effect re-runs and on unmount',
      'After every render, unconditionally',
      'It never runs in StrictMode',
    ],
    correctIndex: 1,
    explanation: 'Cleanup runs before the effect re-executes after a dependency change, and on unmount. StrictMode double-invokes effects in development precisely to surface bugs in this logic.',
    hint: 'Think dependency changes plus unmounting.',
    difficulty: 'intermediate',
  },
  {
    id: 'react-state-batch',
    topic: 'React',
    prompt: 'Starting from `count = 0`, what renders after `setCount(count + 1); setCount(count + 1);` in one handler?',
    options: ['1', '2', '0', 'NaN'],
    correctIndex: 0,
    explanation: 'Each render has its own state snapshot, so both updates queue from 0 and the result is 1. The functional form `setCount(c => c + 1)` chains updates instead.',
    hint: 'Each render sees its own snapshot of state.',
    difficulty: 'beginner',
  },
  {
    id: 'react-hooks-order',
    topic: 'React',
    prompt: 'Why must Hooks run in the same order on every render?',
    options: [
      'An ESLint style preference',
      'React matches state to Hook calls by call order',
      'Closures would capture stale props',
      'It avoids extra re-renders',
    ],
    correctIndex: 1,
    explanation: 'Hooks are stored in an ordered list on the component fiber, indexed by call order. Conditional Hook calls desynchronize that list, so state lands on the wrong Hook.',
    hint: 'Think how React knows which state belongs to which useState.',
    difficulty: 'intermediate',
  },
  {
    id: 'css-specificity',
    topic: 'CSS',
    prompt: 'Same element, no `!important` — which rule wins: `#nav .link` vs `ul li a.active`?',
    options: [
      '`ul li a.active`, because it has more selectors',
      '`#nav .link`, because one ID outranks any classes',
      'Whichever comes later always wins',
      'They tie, so the first one wins',
    ],
    correctIndex: 1,
    explanation: 'Specificity compares ID, class, and element columns in order: a single ID outranks any number of classes or elements. Source order only breaks exact ties.',
    hint: 'Count ID selectors first.',
    difficulty: 'intermediate',
  },
  {
    id: 'css-boxmodel',
    topic: 'CSS',
    prompt: 'With `box-sizing: content-box`, how wide does `width: 100px; padding: 10px;` render (left + right)?',
    options: ['100px', '120px', '110px', 'It depends on the margin'],
    correctIndex: 1,
    explanation: 'Under `content-box`, padding and borders add outside the declared width (100 + 10 + 10). `border-box` includes them instead; margins never count toward the width.',
    hint: '`content-box` adds padding outside the declared width.',
    difficulty: 'beginner',
  },
  {
    id: 'ts-generics',
    topic: 'TypeScript',
    prompt: 'What does `function first<T>(arr: T[]): T | undefined` guarantee?',
    options: [
      'It always returns an element',
      'The return type matches the array element type',
      'It only accepts number arrays',
      'It narrows the argument to a subtype',
    ],
    correctIndex: 1,
    explanation: '`T` is inferred from the argument, so the return type tracks the element type exactly. The `| undefined` accounts for empty arrays.',
    hint: '`T` is inferred from the argument you pass in.',
    difficulty: 'intermediate',
  },
  {
    id: 'ts-narrowing',
    topic: 'TypeScript',
    prompt: 'For `let v: string | number`, which check lets TypeScript treat `v` as a number afterwards?',
    options: ['`typeof v === "number"`', '`v == Number`', '`Boolean(v)`', '`v instanceof Number`'],
    correctIndex: 0,
    explanation: '`typeof` guards narrow union types in the following code. Loose equality does not narrow, `Boolean` yields a boolean, and `instanceof Number` only matches wrapper objects.',
    hint: '`typeof` guards narrow union types.',
    difficulty: 'beginner',
  },
  {
    id: 'nextjs-fetch-cache',
    topic: 'Next.js',
    prompt: 'In the Next.js App Router, what does `fetch(url, { cache: "no-store" })` do?',
    options: [
      'Caches the response forever',
      'Skips the cache — always fetches fresh',
      'Enables background revalidation',
      'Only dedupes within one render',
    ],
    correctIndex: 1,
    explanation: '`no-store` opts out of the Data Cache so the fetch runs dynamically on every request. The default caches, `revalidate: N` refreshes on an interval, and deduping happens regardless.',
    hint: 'Think opting out of caching entirely.',
    difficulty: 'intermediate',
  },
];
